### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/tracmailman#1]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. More information can be found in the [blog post](http://trac-hacks.org/blog/2015-02-21-trac-hacks-on-github).

Kind regards,
Ryan

(Apologies if I open a ticket against two of your plugins. I'm doing a manual search of GitHub to find Trac plugins and invite plugin authors; it's sometimes difficult to keep everything straight).

**Comment by weaverba137** [comment]
Thank you for your invitation.  I want to investigate the workflow on trac-hacks a bit more, but I don't think there would be anything preventing such a move eventually.

Also, you should take a look at another package I have, trac-remote, which is not a plugin, but intends to allow one to perform some of the functions of trac-admin on remote servers, _i.e._ one does not have to have login access to the Trac server to run it.

**Comment by rjollos** [comment]
Thanks for the reply. This request is just to move your repository into the trac-hacks GitHub organization, so we don't have any special workflow (or perhaps I'm misunderstanding your statement?). I tried to only open a single ticket for each plugin author that I found on GitHub, but I welcome all of your plugins to the organization. I'll send you an invite now.

**Comment by rjollos** [comment]
You should have received an invite to join the trac-hacks organization just now. Should you choose to proceed, you'll have general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. After you transfer the repository I'll remove you from the Admin team, create an Admin group for your repository and make you the Admin for your repository.

**Comment by weaverba137** [comment]
Ah, right, for some reason I thought you were talking about an external repository, not a GitHub organization/group.  I'll respond to that invitation when I get a chance.

**Comment by weaverba137** [comment]
Transfer complete.  Please double-check the group permissions.

**Comment by rjollos** [comment]
Looks good. Thanks!
